echo --------------------------- Creating separate docker network...
docker network create --subnet=192.16.0.0/24 monitoring_logging
echo --------------------------- Pulling images...
docker-compose pull
echo --------------------------- Building images...
docker-compose build
echo --------------------------- Starting containers...
docker-compose up -d --force-recreate --build
echo --------------------------- Output from 'docker ps'...
docker ps
echo ---------------------------
